name: Build Ionic APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js for Ionic/Vite
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      # cli has to be global otherwise cannot find it
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: npm install
        run: npm ci
      # Install dependencies
      - name: Build Ionic App
        run: |
          ionic build
          ionic cap sync android
          ionic cap copy android
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
          VITE_MAP_ID: ${{ secrets.VITE_MAP_ID }}

      # Set up Java for Gradle
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      # Build APK
      - name: Build APK
        working-directory: android
        run: ./gradlew assembleRelease
        env:
          VITE_MAP_ID: ${{ secrets.VITE_MAP_ID }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: v1.0.0  
      #     release_name: Release v1.0.0
      #     draft: false
      #     prerelease: false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Get Release Upload URL
        id: get_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            // Remove the URI template part and add the name parameter
            const baseUrl = release.data.upload_url.replace(/\{\?.*\}$/, '');
            const uploadUrl = `${baseUrl}?name=app-release.apk`;
            core.setOutput('upload_url', uploadUrl);

      - name: Debug Upload URL
        run: echo ${{ steps.get_release.outputs.upload_url }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: android/app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

