name: Build Ionic APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js for Ionic/Vite
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      # cli has to be global otherwise cannot find it
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: npm install
        run: npm ci
      # Install dependencies
      - name: Build Ionic App
        run: |
          ionic build
          ionic cap sync android
          ionic cap copy android
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
          VITE_MAP_ID: ${{ secrets.VITE_MAP_ID }}

      # Set up Java for Gradle
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      # Build APK
      - name: Clean and build APK
        working-directory: android
        run: ./gradlew clean assembleRelease -P VITE_MAP_ID=${{ secrets.VITE_MAP_ID }}
      - name: Check folder structure
        run: ls -R android/app/build/outputs/apk/release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  
          release_name: Release v1.0.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          asset_name: app-release-unsigned.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

